apiVersion: v1
kind: Namespace
metadata:
  name: spexity-cicd
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gh-deployer
  namespace: spexity-cicd
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gh-deployer-namespaced
rules:
  - apiGroups: [ "apps" ]
    resources: [ "deployments","replicasets" ]
    verbs: [ "get", "list", "watch", "create", "update", "patch", "delete" ]
  - apiGroups: [ "" ]
    resources: [ "services", "configmaps" ]
    verbs: [ "get", "list", "watch", "create", "update", "patch", "delete" ]
  - apiGroups: [ "networking.k8s.io" ]
    resources: [ "ingresses" ]
    verbs: [ "get", "list", "watch", "create", "update", "patch", "delete" ]
  - apiGroups: [ "traefik.io" ]
    resources: [ "middlewares" ]
    verbs: [ "get", "list", "watch", "create", "update", "patch", "delete" ]
  - apiGroups: [ "apps" ]
    resources: [ "statefulsets", "daemonsets" ]
    verbs: [ "get", "list", "watch" ]
  - apiGroups: [ "" ]
    resources: [ "pods" ]
    verbs: [ "get", "list", "watch" ]
