host: "changeme.spexity.net"

oidc:
  clientId: 'spexity-non-prod'
  authServerUrl: 'https://id.spexity.net/realms/spexity-non-prod'

backend:
  tag: "changeme"
  datasource:
    secretName: "spexity-backend-db"

web:
  tag: "changeme"
