apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "spexity.fullname" . }}-backend
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
    traefik.ingress.kubernetes.io/router.middlewares: "{{ .Release.Namespace }}-compress@kubernetescrd"
spec:
  ingressClassName: traefik
  rules:
    - host: {{ .Values.host | quote }}
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: {{ include "spexity.fullname" . }}-backend
                port:
                  number: 8080
