apiVersion: v1
kind: Service
metadata:
  name: {{ include "spexity.fullname" . }}-backend
  labels:
    app.kubernetes.io/name: spexity-backend
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: spexity-backend
  ports:
    - name: http
      port: 8080
      targetPort: http
