name: spexity-dev-harness
services:
  db:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: 'test'
      POSTGRES_PASSWORD: 'test'
      POSTGRES_DB: 'spexity'
    ports:
      - '55432:5432'
    restart: unless-stopped
