name: spexity-dev-harness
services:
  db:
    image: postgres
    container_name: db
    environment:
      POSTGRES_USER: 'myuser'
      POSTGRES_PASSWORD: 'mypassword'
      POSTGRES_DB: 'spexity'
    ports:
      - '55432:5432'
    restart: unless-stopped
