name: Test

on:
  pull_request:
    branches:
      - main
    paths:
      - "backend/**"
      - "web/**"
      - "e2e-tests/**"
      - ".github/workflows/test.yml"
  push:
    branches:
      - main
    paths:
      - "backend/**"
      - "web/**"
      - "e2e-tests/**"
      - ".github/workflows/test.yml"

permissions:
  contents: read

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '25'
          cache: 'maven'
          cache-dependency-path: backend/pom.xml
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm
          cache-dependency-path: |
            web/package-lock.json
            e2e-tests/package-lock.json
      - name: Get Playwright Cache Lock
        working-directory: e2e-tests
        run: |
          echo "PLAYWRIGHT_CACHE_LOCK=$(sha256sum package-lock.json | awk '{print $1}')" >> $GITHUB_ENV
      - name: Cache Playwright
        uses: actions/cache@v4
        id: playwright-cache
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ env.PLAYWRIGHT_CACHE_LOCK }}
      - name: Full test
        run: ./test.sh
      - name: Publish Playwright reports
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: e2e-tests/playwright-report/
          retention-days: 30
